// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_content_delivery_bucket": "myblogv3-20190928113354-hostingbucket-prod",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "http://myblogv3-20190928113354-hostingbucket-prod.s3-website-ap-southeast-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "ap-southeast-2:14909423-acfd-4cb5-88df-66e1d7860157",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_PncCR60DV",
    "aws_user_pools_web_client_id": "6msligr3bpknl1dia5hi5980ub",
    "oauth": {
        "domain": "devapi-prod.auth.ap-southeast-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:8000/",
        "redirectSignOut": "http://localhost:8000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://mk5mgquy5vc2lcao3e3ugyweuy.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-727qszvozjfjpm52qhca3w5msa"
};


export default awsmobile;
